#pragma once

#define MSG_BUFFER_SIZE 50
#define RECONNECTION_TIME 1000
#define HTTP_SERVER_PORT 80

#define BOILER_PIN 26
#define TEMP_PROBE_PIN 34

#define COFFEE_TEMP_STOP_CELSIUS 95
#define COFFEE_TEMP_START_CELSIUS 85

#define AUTO_OFF_TIME_MINUTES 5

#define INPUT_VOLTS 3.3
#define KNOWN_RESISTOR_OHM 50000
